services:
  configsvr:
    image: mongo:8.0
    hostname: configsvr
    command: >
      mongod --configsvr --replSet configRS --port 27019
      --bind_ip_all
      --setParameter enableTestCommands=1
    ports:
      - "27019:27019"
    networks:
      - mongonet

  shard0:
    image: mongo:8.0
    hostname: shard0
    command: >
      mongod --shardsvr --replSet shard0RS --port 27018
      --bind_ip_all
      --setParameter enableTestCommands=1
    ports:
      - "27018:27018"
    networks:
      - mongonet

  shard1:
    image: mongo:8.0
    hostname: shard1
    command: >
      mongod --shardsvr --replSet shard1RS --port 27018
      --bind_ip_all
      --setParameter enableTestCommands=1
    ports:
      - "27028:27018"
    networks:
      - mongonet

  mongos:
    image: mongo:8.0
    hostname: mongos
    command: >
      mongos --configdb configRS/configsvr:27019 --port 27017
      --bind_ip_all
      --setParameter enableTestCommands=1
    ports:
      - "27017:27017"
    depends_on:
      - configsvr
    networks:
      - mongonet

networks:
  mongonet:
    driver: bridge
