api_version: 3
builders:
- args:
    template_file:
    - master_template.yml
    - aws_template.yml
    - azure_template.yml
  path: nvflare.lighter.impl.workspace.WorkspaceBuilder
- args:
    config_folder: config
  path: nvflare.lighter.impl.static_file.StaticFileBuilder
- path: nvflare.lighter.impl.cert.CertBuilder
- path: nvflare.lighter.impl.signature.SignatureBuilder
description: NVIDIA FLARE sample project yaml file
name: example_project
participants:
- default_host: localhost
  fed_learn_port: 8002
  name: server
  org: nvidia
  type: server
- name: admin@nvidia.com
  org: nvidia
  role: project_admin
  type: admin
- name: org-admin@nvidia.com
  org: nvidia
  role: org_admin
  type: admin
- name: lead@nvidia.com
  org: nvidia
  role: lead
  type: admin
- name: site-1
  org: nvidia
  type: client
- name: site-2
  org: nvidia
  type: client
