<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>DotNext</RootNamespace>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>true</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" PrivateAssets="all" />
    <PackageReference Include="xunit.v3.mtp-v2" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../artifact/dotNext/src/cluster/DotNext.AspNetCore.Cluster/DotNext.AspNetCore.Cluster.csproj" />
    <ProjectReference Include="../artifact/dotNext/src/cluster/DotNext.Net.Cluster/DotNext.Net.Cluster.csproj" />
    <ProjectReference Include="../artifact/dotNext/src/DotNext.IO/DotNext.IO.csproj" />
    <ProjectReference Include="../artifact/dotNext/src/DotNext.Threading/DotNext.Threading.csproj" />
    <ProjectReference Include="../artifact/dotNext/src/DotNext/DotNext.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
