services:
  configsvr:
    image: mongo:latest
    container_name: rdsec-configsvr
    command: >-
      mongod --configsvr --replSet configrs --port 27019 --bind_ip_all
      --setParameter enableTestCommands=1
    networks:
      - rdsec

  shard0pri:
    image: mongo:latest
    container_name: rdsec-shard0pri
    command: >-
      mongod --shardsvr --replSet shard0rs --port 27018 --bind_ip_all
      --setParameter enableTestCommands=1
      --setParameter orphanCleanupDelaySecs=0
      --setParameter 'logComponentVerbosity={sharding: {rangeDeleter: {verbosity: 3}}, replication: {verbosity: 2}}'
    networks:
      - rdsec

  shard0sec:
    image: mongo:latest
    container_name: rdsec-shard0sec
    command: >-
      mongod --shardsvr --replSet shard0rs --port 27018 --bind_ip_all
      --setParameter enableTestCommands=1
      --setParameter orphanCleanupDelaySecs=0
      --setParameter 'logComponentVerbosity={sharding: {rangeDeleter: {verbosity: 3}}, replication: {verbosity: 2}}'
    networks:
      - rdsec

  shard1:
    image: mongo:latest
    container_name: rdsec-shard1
    command: >-
      mongod --shardsvr --replSet shard1rs --port 27018 --bind_ip_all
      --setParameter enableTestCommands=1
      --setParameter orphanCleanupDelaySecs=0
    networks:
      - rdsec

  mongos:
    image: mongo:latest
    container_name: rdsec-mongos
    command: >-
      mongos --configdb configrs/configsvr:27019 --bind_ip_all
      --setParameter enableTestCommands=1
    depends_on:
      - configsvr
      - shard0pri
      - shard0sec
      - shard1
    networks:
      - rdsec

networks:
  rdsec:
