[package]
name = "deque-repro"
version = "0.0.1"
edition = "2021"
publish = false

[[bin]]
name = "test_neg_repro_sanity"
path = "test_neg_repro_sanity.rs"

[[bin]]
name = "test_neg_repro_resize_race"
path = "test_neg_repro_resize_race.rs"

[dependencies]
crossbeam-deque = { path = "../../artifact/crossbeam/crossbeam-deque" }
