services:
  configsvr:
    image: mongo:8
    container_name: repro-configsvr
    hostname: configsvr
    command: >
      mongod --configsvr --replSet configRS --port 27017 --bind_ip_all
      --setParameter enableTestCommands=1
    ports:
      - "47018:27017"
    networks:
      - repronet

  shard0a:
    image: mongo:8
    container_name: repro-shard0a
    hostname: shard0a
    command: >
      mongod --shardsvr --replSet shard0RS --port 27017 --bind_ip_all
      --setParameter enableTestCommands=1
      --setParameter logComponentVerbosity={sharding:{rangeDeleter:{verbosity:2},migration:{verbosity:2}}}
    ports:
      - "47019:27017"
    networks:
      - repronet

  shard0b:
    image: mongo:8
    container_name: repro-shard0b
    hostname: shard0b
    command: >
      mongod --shardsvr --replSet shard0RS --port 27017 --bind_ip_all
      --setParameter enableTestCommands=1
      --setParameter logComponentVerbosity={sharding:{rangeDeleter:{verbosity:2},migration:{verbosity:2}}}
    ports:
      - "47020:27017"
    networks:
      - repronet

  shard1:
    image: mongo:8
    container_name: repro-shard1
    hostname: shard1
    command: >
      mongod --shardsvr --replSet shard1RS --port 27017 --bind_ip_all
      --setParameter enableTestCommands=1
    ports:
      - "47021:27017"
    networks:
      - repronet

  mongos:
    image: mongo:8
    container_name: repro-mongos
    hostname: mongos
    command: >
      mongos --configdb configRS/configsvr:27017 --bind_ip_all --port 27017
      --setParameter enableTestCommands=1
    depends_on:
      - configsvr
    ports:
      - "47017:27017"
    networks:
      - repronet

networks:
  repronet:
    driver: bridge
