from pathlib import Path
import re,json
O=Path(__file__).parent
cfg={}
for f in sorted(O.glob('MC_hunt_*.cfg')):
    lines=[x.strip() for x in f.read_text().splitlines() if not x.lstrip().startswith('\\*')]
    cfg[f.name]=lines[lines.index('INVARIANTS')+1:]
props=['CurrentExecutionConsistency','AcknowledgedResetExists','ImmediateRetryIdentity','FencedOldAttempt','ReapplyProvenance','ReachableHistoryRetained']
base=(O/'base.tla').read_text().splitlines()
text='''# Brief coverage self-audit

This audit was generated by reading the actual hunt cfg files after Phase 2. It maps the supplied brief, not a generic fault taxonomy. All five §2 scenarios, six §5 safety invariants, and three §6.1 questions are accounted for. A cfg mapping means the question is enabled and reachable under its bounds; it does not mean the hunt completed or the implementation was validated.

## §2 scenarios and user priorities

| Scenario / priority | Target configs | Mechanism and reachability |
|---|---|---|
| S1 / Q2 request identity | `MC_hunt_scenario1_2_replay_{sql,cassandra}.cfg` | Explicit merger into S2 recovery. Start → CAN → delete current → Reset → successful/lost response → identical replay or uncertain commit → reload. Original Start identity reaches both CreateRequestId and callback; a fresh UUID on retry is preserved. Known T-1 is regression evidence, never a new MC-discovered defect. |
| S2 / Q1 missing current | `MC_hunt_scenario2_{sql,cassandra}.cfg`; `MC_hunt_scenario2_liveness.cfg` | Supported setup, separate fork/history/base/create, one definite rejection, two uncertain returns, process loss, RangeID renewal, durable lookup and reactive retry. Returned unknown can precede or follow commit. The temporary base link is permitted. |
| S3 / Q3 competing operations | `MC_hunt_scenario3_{sql,sql_io1,cassandra}.cfg` | Seven IDs, two operation slots, A→B→C then delete C leaves two different possible bases. Two distinct reset requests and a competing Start are enabled; same-base leases, short current lookup, per-call I/O and actual expected-current/version/RangeID conditions are retained. SQL slot-1 and slot-2 differ; Cassandra stays at one. |
| S4 / Q4 reapplication | `MC_hunt_scenario4_{sql,cassandra}.cfg` | Two CANs, two Update inputs (same or distinct ID), one Signal, successor deletion, transient read failure and crash. Nonempty-prefix map, original suffix token, missing-versus-failed successor, eligible event provenance and collision error are represented. Buffered termination-time events and alternate storage tokens are explicit gaps in model-notes.md. |
| S5 / Q5 deletion | `MC_hunt_scenario5_{sql,cassandra}.cfg` | Two public deletions, two CANs, age-triggered scanner, uncertain write and crash; branch registration, independent reference snapshot and backend-specific removal. Returned-run deletion is excluded from survivor guarantees; deleting a different source is tested. Default-age configs enforce the History-RPC-deadline-before-scanner-age relation; `MC_hunt_scenario5_short_age_sql.cfg` retains the shorter-age sensitivity experiment. |

## §5 safety invariant enablement

All operators are defined in `base.tla`, exported by `MC.tla` through `EXTENDS base`, and checked by the following **uncommented** cfg entries. The standard `MC.cfg` comments out extension checks.

| Invariant | Definition | Enabled hunt cfgs |
|---|---|---|
'''
for p in props:
    enabled=[f'`{f}`' for f,lines in cfg.items() if p in lines]
    assert enabled,p
    line=next(i for i,x in enumerate(base,1) if x.startswith(p+' =='))
    text+=f'| {p} | `base.tla:{line}` | '+', '.join(enabled)+' |\n'
text+='''
AcknowledgedResetExists and ReapplyProvenance jointly check availability/base/prefix and the eligible reapply result. Post-ack history additions are permitted. These are monitors on completed outcomes, not action guards. ImmediateRetryIdentity has a distinct-operation interference monitor, so it makes no global/permanent-dedup claim.

## §6.1 model-checkable questions

| Finding | Enabled properties and hunt | Fault setup / path |
|---|---|---|
| MC-1 | AcknowledgedResetExists, FencedOldAttempt in S2; HealthyRetryRecovers in S2 liveness | At base/create `ready`, uncertain result can return before `CommitWorkflowExecution`, release the cache, renew RangeID, then resolve old write. At `committed`, the same uncertainty action models commit with lost response. Definite rejection and full process/cache loss are separately reachable. |
| MC-2 | CurrentExecutionConsistency and FencedOldAttempt in S3; availability also enabled | Different retained bases after two CANs; competing Start admitted after missing-current lookup; delayed write before/after ownership change. BrandNew conflicts without replacing current. Handler retry can intentionally terminate the winner. |
| MC-3 | ReapplyProvenance / AcknowledgedResetExists in S4; ReachableHistoryRetained / ReapplyProvenance in S5 | Intermediate successor lookup releases its lease before history read, permitting deletion. NotFound truncates only the actual chain. A fork reference protects shared ancestor cells before new execution creation. Cleanup uses a separately captured reference plan. |

## Test/review handoff and explicit gaps

- T-1 / CR-1: preserved unchanged identity selection and callback contract. The merged S1/S2 cfg enables the known failing property; it must be triaged as known test behavior if found. Use exact replay after both delivered and discarded success on each persistence path for any repair.
- T-2 / CR-2: conflicting valid run-local Update IDs produce Internal before persistence. Source run/payload/completion and exclusion/distinct-ID controls remain representable. No assumed collision repair is encoded. The automatic transient retry wrapper does not label Internal retryable; a further explicit request replay is a bounded client action.
- T-3: pending writes distinguish definite uncommitted rejection, committed unknown response and genuinely delayed completion. This is model setup, not evidence that a live backend fault was injected. Subsequent harness must verify actual commit/readback across process restart.
- CR-3: retained as an unresolved review candidate. `recordchildworkflowcompleted/api.go:28-63,101-107` follows ResetRunId on a closed parent; a missing redirected target may be treated as parent gone by the sender. No supported schedule establishing distinct loss beyond #10639 was provided. Per brief S5's explicit condition, child state/delivery is not added to this suite; the harness/review phase must investigate setup and compensation instead of treating the missing link alone as a bug.
- The model uses DBRecordVersion > 0 records created through supported setup. Legacy nextEventID-only CAS, full wall-clock scheduling beyond the explicit deadline/age order, history batch transaction IDs, retention expiry, buffered events during termination, callback transport, children, and Start conflict-policy variants beyond BrandNew/default rejection are outside this initial suite. Backend-specific acceptance is still required. See model-notes.md for precise abstraction boundaries.
- No guarantee is inferred for an execution that the user explicitly deleted, for infinite persistence failure, for an exhausted finite run pool, or for an uncompleted search.

## Current upstream context

Source semantics are pinned independently of later changes. The supplied analysis archaeology remains the detailed discussion ledger. This generation additionally attempted live reads of [#10926](https://github.com/temporalio/temporal/pull/10926), [#2140](https://github.com/temporalio/temporal/issues/2140), [#6513](https://github.com/temporalio/temporal/pull/6513), and [#6375](https://github.com/temporalio/temporal/issues/6375). Issue reads succeeded. After the PR web pages returned errors, direct GitHub API reads succeeded for #10926, #6513 and [#9479](https://github.com/temporalio/temporal/pull/9479); captured metadata/body are in `validation/upstream-pr-*.json`. #10926 describes the missing-current BrandNew path; #9479 describes preserving the original Start identity for scheduler callbacks; #6513 concerns registry checks for completed Update reapplication. Those contracts inform the pinned model, and no historical repair is reverted in a fault action. Search results were insufficient to establish novelty or a later repair. No upstream-newness or maintainer-confirmation claim is made.
'''
(O/'brief-coverage.md').write_text(text)
(O/'validation'/'coverage-audit.json').write_text(json.dumps({p:[f for f,l in cfg.items() if p in l] for p in props},indent=2)+'\n')
