-------------------------- MODULE SpecControls --------------------------
EXTENDS base, Json, IOUtils
VARIABLE l, records
controlVars == <<s,l,records>>
JsonFile == IF "JSON" \in DOMAIN IOEnv THEN IOEnv.JSON ELSE "../traces/trace.ndjson"
TraceLog == SelectSeq(ndJsonDeserialize(JsonFile),
                     LAMBDA e: IF "tag" \in DOMAIN e THEN e.tag = "trace" ELSE FALSE)
logline == TraceLog[l]
TraceConfig == TraceLog[1].config

\* JSON arrays encode sets and sequences distinctly by the schema, never by guessing.
DecodeAI(j) == [j EXCEPT !.mask = ToSet(@)]
DecodeWF(j) == [j EXCEPT !.ai = [a \in Activities |-> DecodeAI(j.ai[a])],
   !.scheduled = ToSet(@), !.seen = ToSet(@), !.consumed = ToSet(@)]
DecodeReply(j) == [j EXCEPT !.outcome = ToSet(@)]
DecodeWrite(j) == [j EXCEPT !.wf = DecodeWF(@), !.tasks = ToSet(@)]
DecodeState(j) == [j EXCEPT
   !.cache = DecodeWF(@), !.db = DecodeWF(@),
   !.tx.reply = DecodeReply(@),
   !.appended = ToSet(@), !.tasks = ToSet(@), !.claimed = ToSet(@), !.ackable = ToSet(@),
   !.copies = ToSet(@), !.matching = ToSet(@), !.dispatchReturns = ToSet(@),
   !.startCalls = ToSet(@), !.startMsgs = ToSet(@), !.polls = ToSet(@), !.lostStarts = ToSet(@),
   !.tokens = ToSet(@), !.requests = ToSet(@), !.issuedRequests = ToSet(@),
   !.replies = {DecodeReply(j.replies[i]): i \in 1..Len(j.replies)},
   !.pollReplies = {DecodeReply(j.pollReplies[i]): i \in 1..Len(j.pollReplies)},
   !.observed = {DecodeReply(j.observed[i]): i \in 1..Len(j.observed)},
   !.acknowledged = ToSet(@), !.cancelObserved = ToSet(@),
   !.writes = {DecodeWrite(j.writes[i]): i \in 1..Len(j.writes)},
   !.receipts = ToSet(@), !.historyAppends = ToSet(@), !.committedOutcomes = ToSet(@),
   !.notifyPending = ToSet(@), !.notified = ToSet(@),
   !.lastCheck.beforeAI = DecodeAI(@), !.lastCheck.afterAI = DecodeAI(@),
   !.lastCheck.beforeTerms = ToSet(@), !.lastCheck.afterTerms = ToSet(@),
   !.readback.outcomes = ToSet(@)]
TraceActivityCount == TraceConfig.ActivityCount
TraceNamespaceVersion == TraceConfig.NamespaceVersion
TraceIncrementRetryStamp == TraceConfig.IncrementRetryStamp
TraceHasRetryPolicy == TraceConfig.HasRetryPolicy
TraceMaximumAttempts == TraceConfig.MaximumAttempts
TraceInitialInterval == TraceConfig.InitialInterval
TraceBackoffCoefficient == TraceConfig.BackoffCoefficient
TraceMaximumInterval == TraceConfig.MaximumInterval
TraceScheduleToStart == TraceConfig.ScheduleToStart
TraceStartToClose == TraceConfig.StartToClose
TraceScheduleToClose == TraceConfig.ScheduleToClose
TraceHeartbeat == TraceConfig.Heartbeat
TraceWorkflowExpiration == TraceConfig.WorkflowExpiration
TraceKeepInitialWFT == TraceConfig.KeepInitialWFT
TraceInitialDBVersion == TraceConfig.InitialDBVersion
TraceWorkers == ToSet(TraceConfig.Workers)


IsEvent(name) == l <= Len(TraceLog) /\ logline.event = name
ControlEvent(st,name,args,n) == [tag |-> "trace",schemaVersion |-> 1,seq |-> n,
 event |-> name,args |-> args,state |-> st,
 evidence |-> [sourceRevision |-> "0c010ce5fe8c0180aa7573c72fe8fc87c6df7025",
 basis |-> "synthetic-specification-control",complete |-> TRUE,
 ordering |-> "lease-and-transaction",artifact |-> "generated by SpecControls; not an implementation trace"]]
ControlInit == Init /\ l = 2 /\ records = <<
 ([config |-> TraceConfig] @@ ControlEvent(s,"Bootstrap",[k \in {} |-> k],1))>>
Capture == records' = Append(records,ControlEvent(s',logline.event,logline.args,l))
ControlAddActivityTaskScheduledEvent ==
  /\ IsEvent("AddActivityTaskScheduledEvent")
  /\ LET e == logline IN DOMAIN e.args = {} /\ AddActivityTaskScheduledEvent
  /\ Capture /\ l' = l+1

ControlProcessActivityTask ==
  /\ IsEvent("ProcessActivityTask")
  /\ LET e == logline IN DOMAIN e.args = {"task"} /\ ProcessActivityTask(e.args.task)
  /\ Capture /\ l' = l+1

ControlExecuteActivityRetryTimerTask ==
  /\ IsEvent("ExecuteActivityRetryTimerTask")
  /\ LET e == logline IN DOMAIN e.args = {"task"} /\ ExecuteActivityRetryTimerTask(e.args.task)
  /\ Capture /\ l' = l+1

ControlDiscardObsoleteActivityTask ==
  /\ IsEvent("DiscardObsoleteActivityTask")
  /\ LET e == logline IN DOMAIN e.args = {"task"} /\ DiscardObsoleteActivityTask(e.args.task)
  /\ Capture /\ l' = l+1

ControlAddActivityTask ==
  /\ IsEvent("AddActivityTask")
  /\ LET e == logline IN DOMAIN e.args = {"delivery","created"} /\ AddActivityTaskAt(e.args.delivery,e.args.created)
  /\ Capture /\ l' = l+1

ControlDeliverAddActivityTaskResponse ==
  /\ IsEvent("DeliverAddActivityTaskResponse")
  /\ LET e == logline IN DOMAIN e.args = {"id"} /\ DeliverAddActivityTaskResponse(e.args.id)
  /\ Capture /\ l' = l+1

ControlLoseAddActivityTaskResponse ==
  /\ IsEvent("LoseAddActivityTaskResponse")
  /\ LET e == logline IN DOMAIN e.args = {"id"} /\ LoseAddActivityTaskResponse(e.args.id)
  /\ Capture /\ l' = l+1

ControlPollActivityTaskQueue ==
  /\ IsEvent("PollActivityTaskQueue")
  /\ LET e == logline IN DOMAIN e.args = {"delivery","worker"} /\ PollActivityTaskQueue(e.args.delivery,e.args.worker)
  /\ Capture /\ l' = l+1

ControlRetryRecordActivityTaskStarted ==
  /\ IsEvent("RetryRecordActivityTaskStarted")
  /\ LET e == logline IN DOMAIN e.args = {"call"} /\ RetryRecordActivityTaskStarted(e.args.call)
  /\ Capture /\ l' = l+1

ControlRecordActivityTaskStarted ==
  /\ IsEvent("RecordActivityTaskStarted")
  /\ LET e == logline IN DOMAIN e.args = {"call"} /\ RecordActivityTaskStarted(e.args.call)
  /\ Capture /\ l' = l+1

ControlRecordActivityTaskStartedDuplicate ==
  /\ IsEvent("RecordActivityTaskStartedDuplicate")
  /\ LET e == logline IN DOMAIN e.args = {"call"} /\ RecordActivityTaskStartedDuplicate(e.args.call)
  /\ Capture /\ l' = l+1

ControlRecordActivityTaskStartedRejected ==
  /\ IsEvent("RecordActivityTaskStartedRejected")
  /\ LET e == logline IN DOMAIN e.args = {"call"} /\ RecordActivityTaskStartedRejected(e.args.call)
  /\ Capture /\ l' = l+1

ControlSendActivityRequest ==
  /\ IsEvent("SendActivityRequest")
  /\ LET e == logline IN DOMAIN e.args = {"token","kind","details"} /\ SendActivityRequest(e.args.token,e.args.kind,e.args.details)
  /\ Capture /\ l' = l+1

ControlRespondActivityTaskCompleted ==
  /\ IsEvent("RespondActivityTaskCompleted")
  /\ LET e == logline IN DOMAIN e.args = {"request"} /\ RespondActivityTaskCompleted(e.args.request)
  /\ Capture /\ l' = l+1

ControlRespondActivityTaskFailed ==
  /\ IsEvent("RespondActivityTaskFailed")
  /\ LET e == logline IN DOMAIN e.args = {"request"} /\ RespondActivityTaskFailed(e.args.request)
  /\ Capture /\ l' = l+1

ControlRespondActivityTaskCanceled ==
  /\ IsEvent("RespondActivityTaskCanceled")
  /\ LET e == logline IN DOMAIN e.args = {"request"} /\ RespondActivityTaskCanceled(e.args.request)
  /\ Capture /\ l' = l+1

ControlRecordActivityTaskHeartbeat ==
  /\ IsEvent("RecordActivityTaskHeartbeat")
  /\ LET e == logline IN DOMAIN e.args = {"request"} /\ RecordActivityTaskHeartbeat(e.args.request)
  /\ Capture /\ l' = l+1

ControlRejectActivityRequest ==
  /\ IsEvent("RejectActivityRequest")
  /\ LET e == logline IN DOMAIN e.args = {"request"} /\ RejectActivityRequest(e.args.request)
  /\ Capture /\ l' = l+1

ControlExecuteActivityTimeoutTask ==
  /\ IsEvent("ExecuteActivityTimeoutTask")
  /\ LET e == logline IN DOMAIN e.args = {"task"} /\ ExecuteActivityTimeoutTask(e.args.task)
  /\ Capture /\ l' = l+1

ControlDiscardClosedWorkflowTimer ==
  /\ IsEvent("DiscardClosedWorkflowTimer")
  /\ LET e == logline IN DOMAIN e.args = {"task"} /\ DiscardClosedWorkflowTimer(e.args.task)
  /\ Capture /\ l' = l+1

ControlRecordWorkflowTaskStarted ==
  /\ IsEvent("RecordWorkflowTaskStarted")
  /\ LET e == logline IN DOMAIN e.args = {} /\ RecordWorkflowTaskStarted
  /\ Capture /\ l' = l+1

ControlRespondWorkflowTaskCompleted ==
  /\ IsEvent("RespondWorkflowTaskCompleted")
  /\ LET e == logline IN DOMAIN e.args = {} /\ RespondWorkflowTaskCompleted
  /\ Capture /\ l' = l+1

ControlHandleCommandRequestCancelActivity ==
  /\ IsEvent("HandleCommandRequestCancelActivity")
  /\ LET e == logline IN DOMAIN e.args = {"activity"} /\ HandleCommandRequestCancelActivity(e.args.activity)
  /\ Capture /\ l' = l+1

ControlHandleCommandCancelBufferedActivity ==
  /\ IsEvent("HandleCommandCancelBufferedActivity")
  /\ LET e == logline IN DOMAIN e.args = {"activity"} /\ HandleCommandCancelBufferedActivity(e.args.activity)
  /\ Capture /\ l' = l+1

ControlHandleCommandCompleteWorkflow ==
  /\ IsEvent("HandleCommandCompleteWorkflow")
  /\ LET e == logline IN DOMAIN e.args = {} /\ HandleCommandCompleteWorkflow
  /\ Capture /\ l' = l+1

ControlHandleCommandCancelAndCompleteWorkflow ==
  /\ IsEvent("HandleCommandCancelAndCompleteWorkflow")
  /\ LET e == logline IN DOMAIN e.args = {"activity"} /\ HandleCommandCancelAndCompleteWorkflow(e.args.activity)
  /\ Capture /\ l' = l+1

ControlExecuteWorkflowRunTimeoutTask ==
  /\ IsEvent("ExecuteWorkflowRunTimeoutTask")
  /\ LET e == logline IN DOMAIN e.args = {} /\ ExecuteWorkflowRunTimeoutTask
  /\ Capture /\ l' = l+1

ControlCloseTransactionAsMutation ==
  /\ IsEvent("CloseTransactionAsMutation")
  /\ LET e == logline IN DOMAIN e.args = {} /\ CloseTransactionAsMutation
  /\ Capture /\ l' = l+1

ControlSetAndTrackTaskKeys ==
  /\ IsEvent("SetAndTrackTaskKeys")
  /\ LET e == logline IN DOMAIN e.args = {"minimum"} /\ SetAndTrackTaskKeysAt(e.args.minimum)
  /\ Capture /\ l' = l+1

ControlAppendHistoryNodes ==
  /\ IsEvent("AppendHistoryNodes")
  /\ LET e == logline IN DOMAIN e.args = {"write"} /\ AppendHistoryNodesFor(DecodeWrite(e.args.write))
  /\ Capture /\ l' = l+1

ControlApplyWorkflowMutationTx ==
  /\ IsEvent("ApplyWorkflowMutationTx")
  /\ LET e == logline IN DOMAIN e.args = {"write"} /\ ApplyWorkflowMutationTx(DecodeWrite(e.args.write))
  /\ Capture /\ l' = l+1

ControlRejectWorkflowMutationTx ==
  /\ IsEvent("RejectWorkflowMutationTx")
  /\ LET e == logline IN DOMAIN e.args = {"write"} /\ RejectWorkflowMutationTx(DecodeWrite(e.args.write))
  /\ Capture /\ l' = l+1

ControlRejectPersistenceWrite ==
  /\ IsEvent("RejectPersistenceWrite")
  /\ LET e == logline IN DOMAIN e.args = {"write"} /\ RejectPersistenceWrite(DecodeWrite(e.args.write))
  /\ Capture /\ l' = l+1

ControlPersistenceTimeoutBeforeWrite ==
  /\ IsEvent("PersistenceTimeoutBeforeWrite")
  /\ LET e == logline IN DOMAIN e.args = {} /\ PersistenceTimeoutBeforeWrite
  /\ Capture /\ l' = l+1

ControlPersistenceResponseTimeout ==
  /\ IsEvent("PersistenceResponseTimeout")
  /\ LET e == logline IN DOMAIN e.args = {} /\ PersistenceResponseTimeout
  /\ Capture /\ l' = l+1

ControlRetryPersistenceAfterUnavailable ==
  /\ IsEvent("RetryPersistenceAfterUnavailable")
  /\ LET e == logline IN DOMAIN e.args = {} /\ RetryPersistenceAfterUnavailable
  /\ Capture /\ l' = l+1

ControlReturnPersistenceResult ==
  /\ IsEvent("ReturnPersistenceResult")
  /\ LET e == logline IN DOMAIN e.args = {} /\ ReturnPersistenceResult
  /\ Capture /\ l' = l+1

ControlFinishUpdateWorkflowExecution ==
  /\ IsEvent("FinishUpdateWorkflowExecution")
  /\ LET e == logline IN DOMAIN e.args = {} /\ FinishUpdateWorkflowExecution
  /\ Capture /\ l' = l+1

ControlClearWorkflowCache ==
  /\ IsEvent("ClearWorkflowCache")
  /\ LET e == logline IN DOMAIN e.args = {} /\ ClearWorkflowCache
  /\ Capture /\ l' = l+1

ControlLoseShardContext ==
  /\ IsEvent("LoseShardContext")
  /\ LET e == logline IN DOMAIN e.args = {} /\ LoseShardContext
  /\ Capture /\ l' = l+1

ControlReacquireShard ==
  /\ IsEvent("ReacquireShard")
  /\ LET e == logline IN DOMAIN e.args = {} /\ ReacquireShard
  /\ Capture /\ l' = l+1

ControlLoadMutableState ==
  /\ IsEvent("LoadMutableState")
  /\ LET e == logline IN DOMAIN e.args = {} /\ LoadMutableState
  /\ Capture /\ l' = l+1

ControlReadWorkflowExecution ==
  /\ IsEvent("ReadWorkflowExecution")
  /\ LET e == logline IN DOMAIN e.args = {} /\ ReadWorkflowExecution
  /\ Capture /\ l' = l+1

ControlNotifyOnExecutionMutation ==
  /\ IsEvent("NotifyOnExecutionMutation")
  /\ LET e == logline IN DOMAIN e.args = {"id"} /\ NotifyOnExecutionMutation(e.args.id)
  /\ Capture /\ l' = l+1

ControlRangeCompleteHistoryTasks ==
  /\ IsEvent("RangeCompleteHistoryTasks")
  /\ LET e == logline IN DOMAIN e.args = {"tasks"} /\ RangeCompleteHistoryTasks(ToSet(e.args.tasks))
  /\ Capture /\ l' = l+1

ControlRedeliverTask ==
  /\ IsEvent("RedeliverTask")
  /\ LET e == logline IN DOMAIN e.args = {"task"} /\ RedeliverTask(e.args.task)
  /\ Capture /\ l' = l+1

ControlReceiveRecordActivityTaskStartedResponse ==
  /\ IsEvent("ReceiveRecordActivityTaskStartedResponse")
  /\ LET e == logline IN DOMAIN e.args = {"response"} /\ ReceiveRecordActivityTaskStartedResponse(DecodeReply(e.args.response))
  /\ Capture /\ l' = l+1

ControlExpireRecordActivityTaskStarted ==
  /\ IsEvent("ExpireRecordActivityTaskStarted")
  /\ LET e == logline IN DOMAIN e.args = {"call"} /\ ExpireRecordActivityTaskStarted(e.args.call)
  /\ Capture /\ l' = l+1

ControlDeliverPollActivityTaskQueueResponse ==
  /\ IsEvent("DeliverPollActivityTaskQueueResponse")
  /\ LET e == logline IN DOMAIN e.args = {"response"} /\ DeliverPollActivityTaskQueueResponse(DecodeReply(e.args.response))
  /\ Capture /\ l' = l+1

ControlDeliverActivityResponse ==
  /\ IsEvent("DeliverActivityResponse")
  /\ LET e == logline IN DOMAIN e.args = {"response"} /\ DeliverActivityResponse(DecodeReply(e.args.response))
  /\ Capture /\ l' = l+1

ControlLoseAPIResponse ==
  /\ IsEvent("LoseAPIResponse")
  /\ LET e == logline IN DOMAIN e.args = {"response"} /\ LoseAPIResponse(DecodeReply(e.args.response))
  /\ Capture /\ l' = l+1

ControlAdvanceTime ==
  /\ IsEvent("AdvanceTime")
  /\ LET e == logline IN DOMAIN e.args = {"time"} /\ AdvanceTime(e.args.time)
  /\ Capture /\ l' = l+1

ControlFinishTrace ==
  /\ IsEvent("FinishTrace")
  /\ LET e == logline IN DOMAIN e.args = {} /\ FinishTrace
  /\ Capture /\ l' = l+1

ControlHandleCommandCompleteWorkflowRejected ==
  /\ IsEvent("HandleCommandCompleteWorkflowRejected")
  /\ LET e == logline IN DOMAIN e.args = {} /\ HandleCommandCompleteWorkflowRejected
  /\ Capture /\ l' = l+1

ControlReloadAfterRejectedWorkflowClose ==
  /\ IsEvent("ReloadAfterRejectedWorkflowClose")
  /\ LET e == logline IN DOMAIN e.args = {} /\ ReloadAfterRejectedWorkflowClose
  /\ Capture /\ l' = l+1

ControlFailWorkflowTaskAfterRejectedClose ==
  /\ IsEvent("FailWorkflowTaskAfterRejectedClose")
  /\ LET e == logline IN DOMAIN e.args = {} /\ FailWorkflowTaskAfterRejectedClose
  /\ Capture /\ l' = l+1

ControlSubmitWorkflowMutation ==
  /\ IsEvent("SubmitWorkflowMutation")
  /\ DOMAIN logline.args = {} /\ SubmitWorkflowMutation
  /\ Capture /\ l' = l+1

ControlShardReady ==
  /\ IsEvent("ShardReady")
  /\ DOMAIN logline.args = {} /\ ShardReady
  /\ Capture /\ l' = l+1

ControlRetryMatchingActivityTask ==
  /\ IsEvent("RetryMatchingActivityTask")
  /\ DOMAIN logline.args = {"call"} /\ RetryMatchingActivityTask(logline.args.call)
  /\ Capture /\ l' = l+1

ControlRetryActivityRequest ==
  /\ IsEvent("RetryActivityRequest")
  /\ DOMAIN logline.args = {"request"} /\ RetryActivityRequest(logline.args.request)
  /\ Capture /\ l' = l+1

ControlDropExpiredMatchingTask ==
  /\ IsEvent("DropExpiredMatchingTask")
  /\ DOMAIN logline.args = {"delivery"} /\ DropExpiredMatchingTask(logline.args.delivery)
  /\ Capture /\ l' = l+1

ControlStep ==
  \/ ControlAddActivityTaskScheduledEvent
  \/ ControlProcessActivityTask
  \/ ControlExecuteActivityRetryTimerTask
  \/ ControlDiscardObsoleteActivityTask
  \/ ControlAddActivityTask
  \/ ControlDeliverAddActivityTaskResponse
  \/ ControlLoseAddActivityTaskResponse
  \/ ControlPollActivityTaskQueue
  \/ ControlRetryRecordActivityTaskStarted
  \/ ControlRecordActivityTaskStarted
  \/ ControlRecordActivityTaskStartedDuplicate
  \/ ControlRecordActivityTaskStartedRejected
  \/ ControlSendActivityRequest
  \/ ControlRespondActivityTaskCompleted
  \/ ControlRespondActivityTaskFailed
  \/ ControlRespondActivityTaskCanceled
  \/ ControlRecordActivityTaskHeartbeat
  \/ ControlRejectActivityRequest
  \/ ControlExecuteActivityTimeoutTask
  \/ ControlDiscardClosedWorkflowTimer
  \/ ControlRecordWorkflowTaskStarted
  \/ ControlRespondWorkflowTaskCompleted
  \/ ControlHandleCommandRequestCancelActivity
  \/ ControlHandleCommandCancelBufferedActivity
  \/ ControlHandleCommandCompleteWorkflow
  \/ ControlHandleCommandCancelAndCompleteWorkflow
  \/ ControlExecuteWorkflowRunTimeoutTask
  \/ ControlCloseTransactionAsMutation
  \/ ControlSetAndTrackTaskKeys
  \/ ControlAppendHistoryNodes
  \/ ControlApplyWorkflowMutationTx
  \/ ControlRejectWorkflowMutationTx
  \/ ControlRejectPersistenceWrite
  \/ ControlPersistenceTimeoutBeforeWrite
  \/ ControlPersistenceResponseTimeout
  \/ ControlRetryPersistenceAfterUnavailable
  \/ ControlReturnPersistenceResult
  \/ ControlFinishUpdateWorkflowExecution
  \/ ControlClearWorkflowCache
  \/ ControlLoseShardContext
  \/ ControlReacquireShard
  \/ ControlLoadMutableState
  \/ ControlReadWorkflowExecution
  \/ ControlNotifyOnExecutionMutation
  \/ ControlRangeCompleteHistoryTasks
  \/ ControlRedeliverTask
  \/ ControlReceiveRecordActivityTaskStartedResponse
  \/ ControlExpireRecordActivityTaskStarted
  \/ ControlDeliverPollActivityTaskQueueResponse
  \/ ControlDeliverActivityResponse
  \/ ControlLoseAPIResponse
  \/ ControlAdvanceTime
  \/ ControlFinishTrace
  \/ ControlHandleCommandCompleteWorkflowRejected
  \/ ControlReloadAfterRejectedWorkflowClose
  \/ ControlFailWorkflowTaskAfterRejectedClose
  \/ ControlSubmitWorkflowMutation
  \/ ControlShardReady
  \/ ControlRetryMatchingActivityTask
  \/ ControlRetryActivityRequest
  \/ ControlDropExpiredMatchingTask
ControlNext == ControlStep \/ (l > Len(TraceLog) /\ UNCHANGED controlVars)
ControlSpec == ControlInit /\ [][ControlNext]_controlVars /\ WF_controlVars(ControlStep)
ControlCompleted == <>(l > Len(TraceLog))
SaveControl == IF l > Len(TraceLog) THEN JsonSerialize(IOEnv.CONTROL_OUTPUT,records) ELSE TRUE
=============================================================================
