services:
  configsvr:
    image: mongo:8
    container_name: cm-configsvr
    command: >
      mongod --configsvr --replSet cfgrs --port 27019
      --bind_ip_all
      --setParameter enableTestCommands=1
    networks:
      - mongo-cluster

  shard0a:
    image: mongo:8
    container_name: cm-shard0a
    command: >
      mongod --shardsvr --replSet shard0rs --port 27018
      --bind_ip_all
      --setParameter enableTestCommands=1
      --setParameter "logComponentVerbosity={sharding: {verbosity: 2}}"
    networks:
      - mongo-cluster

  shard0b:
    image: mongo:8
    container_name: cm-shard0b
    command: >
      mongod --shardsvr --replSet shard0rs --port 27018
      --bind_ip_all
      --setParameter enableTestCommands=1
      --setParameter "logComponentVerbosity={sharding: {verbosity: 2}}"
    networks:
      - mongo-cluster

  shard1:
    image: mongo:8
    container_name: cm-shard1
    command: >
      mongod --shardsvr --replSet shard1rs --port 27018
      --bind_ip_all
      --setParameter enableTestCommands=1
      --setParameter "logComponentVerbosity={sharding: {verbosity: 2}}"
    networks:
      - mongo-cluster

  mongos:
    image: mongo:8
    container_name: cm-mongos
    command: >
      mongos --configdb cfgrs/configsvr:27019 --port 27017
      --bind_ip_all
      --setParameter enableTestCommands=1
    depends_on:
      - configsvr
      - shard0a
      - shard0b
      - shard1
    ports:
      - "27117:27017"
    networks:
      - mongo-cluster

networks:
  mongo-cluster:
    driver: bridge
