#!/usr/bin/env python3
"""Apply trace instrumentation to crossbeam-deque source files.

Patches:
  * crossbeam-deque/src/lib.rs    — add `pub mod tla_trace;`
  * crossbeam-deque/src/deque.rs  — insert trace_emit calls at every
                                    instrumentation point named in
                                    instrumentation-spec.md.

Idempotent: if a marker comment is already present, the file is left alone.
"""

import re
import sys
from pathlib import Path


MARKER = "TLA_TRACE_INSTRUMENTED"


# --------------------------------------------------------------------------
# lib.rs
# --------------------------------------------------------------------------

def patch_lib_rs(path: Path) -> None:
    text = path.read_text()
    if MARKER in text:
        return
    needle = '#[cfg(feature = "std")]\nmod deque;'
    inject = '#[cfg(feature = "std")]\npub mod tla_trace;\n#[cfg(feature = "std")]\nmod deque;'
    if needle not in text:
        sys.exit("lib.rs: anchor for `mod deque;` not found")
    new = text.replace(needle, inject) + f"\n// {MARKER}\n"
    path.write_text(new)


# --------------------------------------------------------------------------
# deque.rs
# --------------------------------------------------------------------------

def replace_unique(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count == 0:
        sys.exit(f"deque.rs: anchor not found for {label}")
    if count > 1:
        sys.exit(f"deque.rs: anchor for {label} matched {count} times — need uniqueness")
    return text.replace(old, new, 1)


def patch_deque_rs(path: Path) -> None:
    text = path.read_text()
    if MARKER in text:
        return

    # ---- Worker::push  (PushWriteSlot + PushStoreBack) ----
    old = (
        "        // Write `task` into the slot.\n"
        "        unsafe {\n"
        "            buffer.write(b, MaybeUninit::new(task));\n"
        "        }\n"
        "\n"
        "        // ThreadSanitizer does not understand fences, so we omit fence and do store with Release ordering.\n"
        "        #[cfg(not(crossbeam_sanitize_thread))]\n"
        "        atomic::fence(Ordering::Release);\n"
        "        let store_order = if cfg!(crossbeam_sanitize_thread) {\n"
        "            Ordering::Release\n"
        "        } else {\n"
        "            Ordering::Relaxed\n"
        "        };\n"
        "\n"
        "        // Increment the back index.\n"
        "        self.inner.back.store(b.wrapping_add(1), store_order);\n"
        "    }\n"
        "\n"
        "    /// Pops a task from the queue.\n"
    )
    new = (
        "        // Write `task` into the slot.\n"
        "        let __tla_val = crate::tla_trace::val_view(&task);\n"
        "        let __tla_t0 = crate::tla_trace::rdtsc();\n"
        "        unsafe {\n"
        "            buffer.write(b, MaybeUninit::new(task));\n"
        "        }\n"
        "        let __tla_t1 = crate::tla_trace::rdtsc();\n"
        "        {\n"
        "            let __st = crate::tla_trace::State {\n"
        "                front: self.inner.front.load(Ordering::SeqCst) as i64,\n"
        "                back: self.inner.back.load(Ordering::Relaxed) as i64,\n"
        "                buf_id: crate::tla_trace::buf_id(self.buffer.get().ptr as usize),\n"
        "            };\n"
        "            crate::tla_trace::emit_push_write_slot(__tla_t0, __tla_t1, __st, __tla_val);\n"
        "        }\n"
        "\n"
        "        // ThreadSanitizer does not understand fences, so we omit fence and do store with Release ordering.\n"
        "        #[cfg(not(crossbeam_sanitize_thread))]\n"
        "        atomic::fence(Ordering::Release);\n"
        "        let store_order = if cfg!(crossbeam_sanitize_thread) {\n"
        "            Ordering::Release\n"
        "        } else {\n"
        "            Ordering::Relaxed\n"
        "        };\n"
        "\n"
        "        // Increment the back index.\n"
        "        let __tla_t2 = crate::tla_trace::rdtsc();\n"
        "        self.inner.back.store(b.wrapping_add(1), store_order);\n"
        "        let __tla_t3 = crate::tla_trace::rdtsc();\n"
        "        {\n"
        "            let __st = crate::tla_trace::State {\n"
        "                front: self.inner.front.load(Ordering::SeqCst) as i64,\n"
        "                back: self.inner.back.load(Ordering::Relaxed) as i64,\n"
        "                buf_id: crate::tla_trace::buf_id(self.buffer.get().ptr as usize),\n"
        "            };\n"
        "            crate::tla_trace::emit_push_store_back(__tla_t2, __tla_t3, __st);\n"
        "        }\n"
        "    }\n"
        "\n"
        "    /// Pops a task from the queue.\n"
    )
    text = replace_unique(text, old, new, "Worker::push")

    # ---- Worker::pop FIFO branch (FIFOPopAttempt + FIFOPopRollback) ----
    old = (
        "            // Pop from the front of the queue.\n"
        "            Flavor::Fifo => {\n"
        "                // Try incrementing the front index to pop the task.\n"
        "                let f = self.inner.front.fetch_add(1, Ordering::SeqCst);\n"
        "                let new_f = f.wrapping_add(1);\n"
        "\n"
        "                if b.wrapping_sub(new_f) < 0 {\n"
        "                    self.inner.front.store(f, Ordering::Relaxed);\n"
        "                    return None;\n"
        "                }\n"
        "\n"
        "                unsafe {\n"
        "                    // Read the popped task.\n"
        "                    let buffer = self.buffer.get();\n"
        "                    let task = buffer.read(f).assume_init();\n"
        "\n"
        "                    // Shrink the buffer if `len - 1` is less than one fourth of the capacity.\n"
        "                    if buffer.cap > MIN_CAP && len <= buffer.cap as isize / 4 {\n"
        "                        self.resize(buffer.cap / 2);\n"
        "                    }\n"
        "\n"
        "                    Some(task)\n"
        "                }\n"
        "            }\n"
    )
    new = (
        "            // Pop from the front of the queue.\n"
        "            Flavor::Fifo => {\n"
        "                // Try incrementing the front index to pop the task.\n"
        "                let __tla_t0 = crate::tla_trace::rdtsc();\n"
        "                let f = self.inner.front.fetch_add(1, Ordering::SeqCst);\n"
        "                let __tla_t1 = crate::tla_trace::rdtsc();\n"
        "                let new_f = f.wrapping_add(1);\n"
        "\n"
        "                if b.wrapping_sub(new_f) < 0 {\n"
        "                    {\n"
        "                        let __st = crate::tla_trace::State {\n"
        "                            front: self.inner.front.load(Ordering::SeqCst) as i64,\n"
        "                            back: self.inner.back.load(Ordering::Relaxed) as i64,\n"
        "                            buf_id: crate::tla_trace::buf_id(self.buffer.get().ptr as usize),\n"
        "                        };\n"
        "                        crate::tla_trace::emit_fifo_pop_attempt(__tla_t0, __tla_t1, __st, \"rollback_needed\", 0);\n"
        "                    }\n"
        "                    let __tla_t2 = crate::tla_trace::rdtsc();\n"
        "                    self.inner.front.store(f, Ordering::Relaxed);\n"
        "                    let __tla_t3 = crate::tla_trace::rdtsc();\n"
        "                    {\n"
        "                        let __st = crate::tla_trace::State {\n"
        "                            front: self.inner.front.load(Ordering::SeqCst) as i64,\n"
        "                            back: self.inner.back.load(Ordering::Relaxed) as i64,\n"
        "                            buf_id: crate::tla_trace::buf_id(self.buffer.get().ptr as usize),\n"
        "                        };\n"
        "                        crate::tla_trace::emit_fifo_pop_rollback(__tla_t2, __tla_t3, __st);\n"
        "                    }\n"
        "                    return None;\n"
        "                }\n"
        "\n"
        "                unsafe {\n"
        "                    // Read the popped task.\n"
        "                    let buffer = self.buffer.get();\n"
        "                    let task = buffer.read(f).assume_init();\n"
        "                    let __tla_val = crate::tla_trace::val_view(&task);\n"
        "                    {\n"
        "                        let __st = crate::tla_trace::State {\n"
        "                            front: self.inner.front.load(Ordering::SeqCst) as i64,\n"
        "                            back: self.inner.back.load(Ordering::Relaxed) as i64,\n"
        "                            buf_id: crate::tla_trace::buf_id(self.buffer.get().ptr as usize),\n"
        "                        };\n"
        "                        crate::tla_trace::emit_fifo_pop_attempt(__tla_t0, __tla_t1, __st, \"success\", __tla_val);\n"
        "                    }\n"
        "\n"
        "                    // Shrink the buffer if `len - 1` is less than one fourth of the capacity.\n"
        "                    if buffer.cap > MIN_CAP && len <= buffer.cap as isize / 4 {\n"
        "                        self.resize(buffer.cap / 2);\n"
        "                    }\n"
        "\n"
        "                    Some(task)\n"
        "                }\n"
        "            }\n"
    )
    text = replace_unique(text, old, new, "Worker::pop FIFO")

    # ---- Worker::pop LIFO branch (LIFOPopDecrFence + LIFOPopDecide) ----
    old = (
        "            // Pop from the back of the queue.\n"
        "            Flavor::Lifo => {\n"
        "                // Decrement the back index.\n"
        "                let b = b.wrapping_sub(1);\n"
        "                self.inner.back.store(b, Ordering::Relaxed);\n"
        "\n"
        "                atomic::fence(Ordering::SeqCst);\n"
        "\n"
        "                // Load the front index.\n"
        "                let f = self.inner.front.load(Ordering::Relaxed);\n"
        "\n"
        "                // Compute the length after the back index was decremented.\n"
        "                let len = b.wrapping_sub(f);\n"
        "\n"
        "                if len < 0 {\n"
        "                    // The queue is empty. Restore the back index to the original task.\n"
        "                    self.inner.back.store(b.wrapping_add(1), Ordering::Relaxed);\n"
        "                    None\n"
        "                } else {\n"
        "                    // Read the task to be popped.\n"
        "                    let buffer = self.buffer.get();\n"
        "                    let mut task = unsafe { Some(buffer.read(b)) };\n"
        "\n"
        "                    // Are we popping the last task from the queue?\n"
        "                    if len == 0 {\n"
        "                        // Try incrementing the front index.\n"
        "                        if self\n"
        "                            .inner\n"
        "                            .front\n"
        "                            .compare_exchange(\n"
        "                                f,\n"
        "                                f.wrapping_add(1),\n"
        "                                Ordering::SeqCst,\n"
        "                                Ordering::Relaxed,\n"
        "                            )\n"
        "                            .is_err()\n"
        "                        {\n"
        "                            // Failed. We didn't pop anything. Reset to `None`.\n"
        "                            task.take();\n"
        "                        }\n"
        "\n"
        "                        // Restore the back index to the original task.\n"
        "                        self.inner.back.store(b.wrapping_add(1), Ordering::Relaxed);\n"
        "                    } else {\n"
        "                        // Shrink the buffer if `len` is less than one fourth of the capacity.\n"
        "                        if buffer.cap > MIN_CAP && len < buffer.cap as isize / 4 {\n"
        "                            unsafe {\n"
        "                                self.resize(buffer.cap / 2);\n"
        "                            }\n"
        "                        }\n"
        "                    }\n"
        "\n"
        "                    task.map(|t| unsafe { t.assume_init() })\n"
        "                }\n"
        "            }\n"
    )
    new = (
        "            // Pop from the back of the queue.\n"
        "            Flavor::Lifo => {\n"
        "                // Decrement the back index.\n"
        "                let __tla_t0 = crate::tla_trace::rdtsc();\n"
        "                let b = b.wrapping_sub(1);\n"
        "                self.inner.back.store(b, Ordering::Relaxed);\n"
        "\n"
        "                atomic::fence(Ordering::SeqCst);\n"
        "\n"
        "                // Load the front index.\n"
        "                let f = self.inner.front.load(Ordering::Relaxed);\n"
        "                let __tla_t1 = crate::tla_trace::rdtsc();\n"
        "                {\n"
        "                    let __st = crate::tla_trace::State {\n"
        "                        front: self.inner.front.load(Ordering::SeqCst) as i64,\n"
        "                        back: self.inner.back.load(Ordering::Relaxed) as i64,\n"
        "                        buf_id: crate::tla_trace::buf_id(self.buffer.get().ptr as usize),\n"
        "                    };\n"
        "                    crate::tla_trace::emit_lifo_pop_decr_fence(__tla_t0, __tla_t1, __st);\n"
        "                }\n"
        "\n"
        "                // Compute the length after the back index was decremented.\n"
        "                let len = b.wrapping_sub(f);\n"
        "\n"
        "                if len < 0 {\n"
        "                    // The queue is empty. Restore the back index to the original task.\n"
        "                    let __tla_t2 = crate::tla_trace::rdtsc();\n"
        "                    self.inner.back.store(b.wrapping_add(1), Ordering::Relaxed);\n"
        "                    let __tla_t3 = crate::tla_trace::rdtsc();\n"
        "                    {\n"
        "                        let __st = crate::tla_trace::State {\n"
        "                            front: self.inner.front.load(Ordering::SeqCst) as i64,\n"
        "                            back: self.inner.back.load(Ordering::Relaxed) as i64,\n"
        "                            buf_id: crate::tla_trace::buf_id(self.buffer.get().ptr as usize),\n"
        "                        };\n"
        "                        crate::tla_trace::emit_lifo_pop_decide(__tla_t2, __tla_t3, __st, \"empty\", 0);\n"
        "                    }\n"
        "                    None\n"
        "                } else {\n"
        "                    // Read the task to be popped.\n"
        "                    let buffer = self.buffer.get();\n"
        "                    let mut task = unsafe { Some(buffer.read(b)) };\n"
        "                    let __tla_val: u64 = match task.as_ref() {\n"
        "                        Some(t) => crate::tla_trace::val_view(t.as_ptr()),\n"
        "                        None => 0,\n"
        "                    };\n"
        "\n"
        "                    // Are we popping the last task from the queue?\n"
        "                    if len == 0 {\n"
        "                        // Try incrementing the front index.\n"
        "                        let __tla_t2 = crate::tla_trace::rdtsc();\n"
        "                        let __tla_cas_ok = self\n"
        "                            .inner\n"
        "                            .front\n"
        "                            .compare_exchange(\n"
        "                                f,\n"
        "                                f.wrapping_add(1),\n"
        "                                Ordering::SeqCst,\n"
        "                                Ordering::Relaxed,\n"
        "                            )\n"
        "                            .is_ok();\n"
        "                        if !__tla_cas_ok {\n"
        "                            // Failed. We didn't pop anything. Reset to `None`.\n"
        "                            task.take();\n"
        "                        }\n"
        "\n"
        "                        // Restore the back index to the original task.\n"
        "                        self.inner.back.store(b.wrapping_add(1), Ordering::Relaxed);\n"
        "                        let __tla_t3 = crate::tla_trace::rdtsc();\n"
        "                        {\n"
        "                            let __st = crate::tla_trace::State {\n"
        "                                front: self.inner.front.load(Ordering::SeqCst) as i64,\n"
        "                                back: self.inner.back.load(Ordering::Relaxed) as i64,\n"
        "                                buf_id: crate::tla_trace::buf_id(self.buffer.get().ptr as usize),\n"
        "                            };\n"
        "                            let __res = if __tla_cas_ok { \"last_cas_success\" } else { \"last_cas_fail\" };\n"
        "                            crate::tla_trace::emit_lifo_pop_decide(__tla_t2, __tla_t3, __st, __res, __tla_val);\n"
        "                        }\n"
        "                    } else {\n"
        "                        let __tla_t2 = crate::tla_trace::rdtsc();\n"
        "                        // Shrink the buffer if `len` is less than one fourth of the capacity.\n"
        "                        if buffer.cap > MIN_CAP && len < buffer.cap as isize / 4 {\n"
        "                            unsafe {\n"
        "                                self.resize(buffer.cap / 2);\n"
        "                            }\n"
        "                        }\n"
        "                        let __tla_t3 = crate::tla_trace::rdtsc();\n"
        "                        {\n"
        "                            let __st = crate::tla_trace::State {\n"
        "                                front: self.inner.front.load(Ordering::SeqCst) as i64,\n"
        "                                back: self.inner.back.load(Ordering::Relaxed) as i64,\n"
        "                                buf_id: crate::tla_trace::buf_id(self.buffer.get().ptr as usize),\n"
        "                            };\n"
        "                            crate::tla_trace::emit_lifo_pop_decide(__tla_t2, __tla_t3, __st, \"multi_pop\", __tla_val);\n"
        "                        }\n"
        "                    }\n"
        "\n"
        "                    task.map(|t| unsafe { t.assume_init() })\n"
        "                }\n"
        "            }\n"
    )
    text = replace_unique(text, old, new, "Worker::pop LIFO")

    # ---- Worker::resize (ResizeGrow) ----
    # The swap returns `old` (the previous shared pointer); emit between swap
    # and `defer_unchecked`.
    old = (
        "        // Replace the old buffer with the new one.\n"
        "        self.buffer.replace(new);\n"
        "        let old =\n"
        "            self.inner\n"
        "                .buffer\n"
        "                .swap(Owned::new(new).into_shared(guard), Ordering::Release, guard);\n"
        "\n"
        "        // Destroy the old buffer later.\n"
        "        unsafe { guard.defer_unchecked(move || old.into_owned().into_box().dealloc()) }\n"
    )
    new = (
        "        // Replace the old buffer with the new one.\n"
        "        let __tla_old_ptr_u = self.buffer.get().ptr as usize;\n"
        "        self.buffer.replace(new);\n"
        "        let __tla_t0 = crate::tla_trace::rdtsc();\n"
        "        let old =\n"
        "            self.inner\n"
        "                .buffer\n"
        "                .swap(Owned::new(new).into_shared(guard), Ordering::Release, guard);\n"
        "        let __tla_t1 = crate::tla_trace::rdtsc();\n"
        "        {\n"
        "            let __st = crate::tla_trace::State {\n"
        "                front: self.inner.front.load(Ordering::SeqCst) as i64,\n"
        "                back: self.inner.back.load(Ordering::Relaxed) as i64,\n"
        "                buf_id: crate::tla_trace::buf_id(self.buffer.get().ptr as usize),\n"
        "            };\n"
        "            let __old_id = crate::tla_trace::buf_id(__tla_old_ptr_u);\n"
        "            crate::tla_trace::emit_resize_grow(__tla_t0, __tla_t1, __st, __old_id);\n"
        "        }\n"
        "\n"
        "        // Destroy the old buffer later.\n"
        "        unsafe { guard.defer_unchecked(move || old.into_owned().into_box().dealloc()) }\n"
    )
    text = replace_unique(text, old, new, "Worker::resize")

    # ---- Stealer::steal (single steal: 6 events) ----
    old = (
        "    pub fn steal(&self) -> Steal<T> {\n"
        "        // Load the front index.\n"
        "        let f = self.inner.front.load(Ordering::Acquire);\n"
        "\n"
        "        // A SeqCst fence is needed here.\n"
        "        //\n"
        "        // If the current thread is already pinned (reentrantly), we must manually issue the\n"
        "        // fence. Otherwise, the following pinning will issue the fence anyway, so we don't\n"
        "        // have to.\n"
        "        if epoch::is_pinned() {\n"
        "            atomic::fence(Ordering::SeqCst);\n"
        "        }\n"
        "\n"
        "        let guard = &epoch::pin();\n"
        "\n"
        "        // Load the back index.\n"
        "        let b = self.inner.back.load(Ordering::Acquire);\n"
        "\n"
        "        // Is the queue empty?\n"
        "        if b.wrapping_sub(f) <= 0 {\n"
        "            return Steal::Empty;\n"
        "        }\n"
        "\n"
        "        // Load the buffer and read the task at the front.\n"
        "        let buffer = self.inner.buffer.load(Ordering::Acquire, guard);\n"
        "        let task = unsafe { buffer.deref().read(f) };\n"
        "\n"
        "        // Try incrementing the front index to steal the task.\n"
        "        // If the buffer has been swapped or the increment fails, we retry.\n"
        "        if self.inner.buffer.load(Ordering::Acquire, guard) != buffer\n"
        "            || self\n"
        "                .inner\n"
        "                .front\n"
        "                .compare_exchange(f, f.wrapping_add(1), Ordering::SeqCst, Ordering::Relaxed)\n"
        "                .is_err()\n"
        "        {\n"
        "            // We didn't steal this task, forget it.\n"
        "            return Steal::Retry;\n"
        "        }\n"
        "\n"
        "        // Return the stolen task.\n"
        "        Steal::Success(unsafe { task.assume_init() })\n"
        "    }\n"
    )
    new = (
        "    pub fn steal(&self) -> Steal<T> {\n"
        "        // Load the front index.\n"
        "        let __tla_t0 = crate::tla_trace::rdtsc();\n"
        "        let f = self.inner.front.load(Ordering::Acquire);\n"
        "        let __tla_t1 = crate::tla_trace::rdtsc();\n"
        "        {\n"
        "            let __st = crate::tla_trace::State {\n"
        "                front: self.inner.front.load(Ordering::SeqCst) as i64,\n"
        "                back: self.inner.back.load(Ordering::Relaxed) as i64,\n"
        "                buf_id: 0,\n"
        "            };\n"
        "            crate::tla_trace::emit_steal_load_front_single(__tla_t0, __tla_t1, __st, f as i64);\n"
        "        }\n"
        "\n"
        "        // A SeqCst fence is needed here.\n"
        "        let __tla_was_pinned = epoch::is_pinned();\n"
        "        let __tla_t2 = crate::tla_trace::rdtsc();\n"
        "        if __tla_was_pinned {\n"
        "            atomic::fence(Ordering::SeqCst);\n"
        "        }\n"
        "\n"
        "        let guard = &epoch::pin();\n"
        "        let __tla_t3 = crate::tla_trace::rdtsc();\n"
        "        {\n"
        "            let __st = crate::tla_trace::State {\n"
        "                front: self.inner.front.load(Ordering::SeqCst) as i64,\n"
        "                back: self.inner.back.load(Ordering::Relaxed) as i64,\n"
        "                buf_id: 0,\n"
        "            };\n"
        "            crate::tla_trace::emit_steal_pin(__tla_t2, __tla_t3, __st, __tla_was_pinned);\n"
        "        }\n"
        "\n"
        "        // Load the back index.\n"
        "        let __tla_t4 = crate::tla_trace::rdtsc();\n"
        "        let b = self.inner.back.load(Ordering::Acquire);\n"
        "        let __tla_t5 = crate::tla_trace::rdtsc();\n"
        "        let __tla_empty = b.wrapping_sub(f) <= 0;\n"
        "        {\n"
        "            let __st = crate::tla_trace::State {\n"
        "                front: self.inner.front.load(Ordering::SeqCst) as i64,\n"
        "                back: self.inner.back.load(Ordering::Relaxed) as i64,\n"
        "                buf_id: 0,\n"
        "            };\n"
        "            let __res = if __tla_empty { \"empty\" } else { \"proceed\" };\n"
        "            crate::tla_trace::emit_steal_load_back(__tla_t4, __tla_t5, __st, b as i64, __res);\n"
        "        }\n"
        "\n"
        "        // Is the queue empty?\n"
        "        if __tla_empty {\n"
        "            return Steal::Empty;\n"
        "        }\n"
        "\n"
        "        // Load the buffer and read the task at the front.\n"
        "        let __tla_t6 = crate::tla_trace::rdtsc();\n"
        "        let buffer = self.inner.buffer.load(Ordering::Acquire, guard);\n"
        "        let __tla_t7 = crate::tla_trace::rdtsc();\n"
        "        let __tla_cached_buf = crate::tla_trace::buf_id(unsafe { buffer.deref() }.ptr as usize);\n"
        "        {\n"
        "            let __st = crate::tla_trace::State {\n"
        "                front: self.inner.front.load(Ordering::SeqCst) as i64,\n"
        "                back: self.inner.back.load(Ordering::Relaxed) as i64,\n"
        "                buf_id: __tla_cached_buf,\n"
        "            };\n"
        "            crate::tla_trace::emit_steal_load_buffer(__tla_t6, __tla_t7, __st, __tla_cached_buf);\n"
        "        }\n"
        "        let __tla_t8 = crate::tla_trace::rdtsc();\n"
        "        let task = unsafe { buffer.deref().read(f) };\n"
        "        let __tla_t9 = crate::tla_trace::rdtsc();\n"
        "        let __tla_read_val: u64 = crate::tla_trace::val_view(task.as_ptr());\n"
        "        {\n"
        "            let __st = crate::tla_trace::State {\n"
        "                front: self.inner.front.load(Ordering::SeqCst) as i64,\n"
        "                back: self.inner.back.load(Ordering::Relaxed) as i64,\n"
        "                buf_id: __tla_cached_buf,\n"
        "            };\n"
        "            crate::tla_trace::emit_steal_read_slot(__tla_t8, __tla_t9, __st, __tla_read_val, __tla_cached_buf);\n"
        "        }\n"
        "\n"
        "        // Try incrementing the front index to steal the task.\n"
        "        let __tla_t10 = crate::tla_trace::rdtsc();\n"
        "        let __tla_buf2 = self.inner.buffer.load(Ordering::Acquire, guard);\n"
        "        let __tla_buf_changed = __tla_buf2 != buffer;\n"
        "        let __tla_cas_ok = if __tla_buf_changed {\n"
        "            false\n"
        "        } else {\n"
        "            self.inner\n"
        "                .front\n"
        "                .compare_exchange(f, f.wrapping_add(1), Ordering::SeqCst, Ordering::Relaxed)\n"
        "                .is_ok()\n"
        "        };\n"
        "        let __tla_t11 = crate::tla_trace::rdtsc();\n"
        "        {\n"
        "            let __st = crate::tla_trace::State {\n"
        "                front: self.inner.front.load(Ordering::SeqCst) as i64,\n"
        "                back: self.inner.back.load(Ordering::Relaxed) as i64,\n"
        "                buf_id: if __tla_buf2.is_null() { 0 } else { crate::tla_trace::buf_id(unsafe { __tla_buf2.deref() }.ptr as usize) },\n"
        "            };\n"
        "            let (__rr, __cr, __sc): (&str, &str, i64) = if __tla_buf_changed {\n"
        "                (\"present_fail\", \"skip_due_to_recheck\", 0)\n"
        "            } else if __tla_cas_ok {\n"
        "                (\"present_pass\", \"success\", 1)\n"
        "            } else {\n"
        "                (\"present_pass\", \"fail_cas\", 0)\n"
        "            };\n"
        "            crate::tla_trace::emit_steal_recheck_cas(__tla_t10, __tla_t11, __st, \"single\", __rr, __cr, __sc);\n"
        "        }\n"
        "        if __tla_buf_changed || !__tla_cas_ok {\n"
        "            return Steal::Retry;\n"
        "        }\n"
        "\n"
        "        // Return the stolen task.\n"
        "        Steal::Success(unsafe { task.assume_init() })\n"
        "    }\n"
    )
    text = replace_unique(text, old, new, "Stealer::steal")

    text += f"\n// {MARKER}\n"
    path.write_text(text)


def main() -> None:
    if len(sys.argv) != 3:
        sys.exit(f"usage: {sys.argv[0]} <lib.rs> <deque.rs>")
    lib_path = Path(sys.argv[1])
    deque_path = Path(sys.argv[2])
    patch_lib_rs(lib_path)
    patch_deque_rs(deque_path)
    print(f"Patched {lib_path}")
    print(f"Patched {deque_path}")


if __name__ == "__main__":
    main()
