services:
  configsvr:
    image: mongo:latest
    container_name: rds-configsvr
    command: mongod --configsvr --replSet configRS --port 27017 --bind_ip_all --setParameter enableTestCommands=1
    networks:
      - rds-net

  shard0a:
    image: mongo:latest
    container_name: rds-shard0a
    command: >
      mongod --shardsvr --replSet shard0RS --port 27017 --bind_ip_all
      --setParameter enableTestCommands=1
      --setParameter "logComponentVerbosity={sharding: {verbosity: 2}}"
    networks:
      - rds-net

  shard0b:
    image: mongo:latest
    container_name: rds-shard0b
    command: >
      mongod --shardsvr --replSet shard0RS --port 27017 --bind_ip_all
      --setParameter enableTestCommands=1
      --setParameter "logComponentVerbosity={sharding: {verbosity: 2}}"
    networks:
      - rds-net

  shard1:
    image: mongo:latest
    container_name: rds-shard1
    command: >
      mongod --shardsvr --replSet shard1RS --port 27017 --bind_ip_all
      --setParameter enableTestCommands=1
    networks:
      - rds-net

  mongos:
    image: mongo:latest
    container_name: rds-mongos
    command: mongos --configdb configRS/configsvr:27017 --bind_ip_all --setParameter enableTestCommands=1
    depends_on:
      - configsvr
    networks:
      - rds-net

networks:
  rds-net:
    driver: bridge
