version: '3.8'
services:
  mongo1:
    image: mongo:latest
    container_name: mongo1
    hostname: mongo1
    command: mongod --replSet rs0 --port 27017 --bind_ip_all --setParameter enableTestCommands=1
    ports:
      - "27017:27017"
    networks:
      - rs0net

  mongo2:
    image: mongo:latest
    container_name: mongo2
    hostname: mongo2
    command: mongod --replSet rs0 --port 27017 --bind_ip_all --setParameter enableTestCommands=1
    ports:
      - "27018:27017"
    networks:
      - rs0net

  mongo3:
    image: mongo:latest
    container_name: mongo3
    hostname: mongo3
    command: mongod --replSet rs0 --port 27017 --bind_ip_all --setParameter enableTestCommands=1
    ports:
      - "27019:27017"
    networks:
      - rs0net

networks:
  rs0net:
    driver: bridge
