---- MODULE base ----
(* Base TLA+ spec for libspdm certificate-based authentication (CHALLENGE/CHALLENGE_AUTH).
   Category A (Distributed/Message-Passing): models SPDM requester/responder endpoints.
   Bug families: 6 (state races, transcript isolation, slot validation, nonce freshness, key source, context echo).
*)

EXTENDS Naturals, FiniteSets, Sequences

(* ============ Constants ============ *)

CONSTANT Requester, Responder
CONSTANT SPDM_VERSION_10, SPDM_VERSION_11, SPDM_VERSION_12, SPDM_VERSION_13
CONSTANT NULL, AUTHENTICATED, CHALLENGED, ONE_WAY_AUTH, MUTUAL_AUTH, FULLY_AUTH
CONSTANT MAIN_TRANSCRIPT, MUTUAL_TRANSCRIPT
CONSTANT CERT_CHAIN, PUBLIC_KEY_ONLY

(* ============ Variables ============ *)

(* Standard protocol state *)
VARIABLE connection_state  \* AUTHENTICATED, CHALLENGED, etc. per endpoint
VARIABLE spdm_version      \* Negotiated version
VARIABLE message_c         \* Main message transcript (CHALLENGE request + response)
VARIABLE message_mut_c     \* Mutual auth message transcript
VARIABLE signature_valid   \* Boolean state of signature verification

(* Bug Family 1: Authentication Phase State *)
VARIABLE authentication_phase  \* {NONE, ONE_WAY_STARTED, ONE_WAY_COMPLETE, MUTUAL_IN_PROGRESS, FULLY_AUTHENTICATED}

(* Bug Family 2: Message Transcript Isolation *)
VARIABLE active_transcript     \* {MAIN, MUTUAL_AUTH} - tracks which transcript is active

(* Bug Family 3: Slot ID Validation *)
VARIABLE slot_id               \* Current slot ID being used
VARIABLE slot_id_valid         \* Boolean: is current slot valid per version rules

(* Bug Family 4: Nonce Freshness *)
VARIABLE nonces_seen           \* Set of nonces observed in current session
VARIABLE responder_nonce       \* Nonce generated by responder
VARIABLE requester_nonce       \* Nonce generated by requester

(* Bug Family 5: Key Source Selection *)
VARIABLE key_source            \* {CERT_CHAIN, PUBLIC_KEY_ONLY} - which hash is used

(* Bug Family 6: Request Context Echo (SPDM 1.3+) *)
VARIABLE requester_context     \* Request context sent by requester
VARIABLE requester_context_in_response  \* Context echoed in response

(* Message passing *)
VARIABLE messages              \* Set of in-flight messages

(* Per-endpoint state tracking *)
VARIABLE endpoint_state        \* Records state for requester and responder separately

vars == <<connection_state, spdm_version, message_c, message_mut_c, signature_valid,
          authentication_phase, active_transcript, slot_id, slot_id_valid,
          nonces_seen, responder_nonce, requester_nonce, key_source,
          requester_context, requester_context_in_response, messages, endpoint_state>>

(* ============ Helpers ============ *)

IsRequester(ep) == ep = Requester
IsResponder(ep) == ep = Responder

GetEndpointState(ep) == endpoint_state[ep]
SetEndpointState(ep, new_state) ==
    [endpoint_state EXCEPT ![ep] = new_state]

VersionSupportsContext(v) == v >= SPDM_VERSION_13

ValidSlotIDForVersion(slot, v) ==
    \/ slot = 255  \* Public key only (all versions)
    \/ /\ slot >= 0
       /\ slot < 8  \* Max 8 slots in typical configs
       /\ v >= SPDM_VERSION_10

(* ============ Init ============ *)

Init ==
    /\ connection_state = NULL
    /\ spdm_version = SPDM_VERSION_10
    /\ message_c = <<>>
    /\ message_mut_c = <<>>
    /\ signature_valid = FALSE
    /\ authentication_phase = "NONE"
    /\ active_transcript = "NONE"
    /\ slot_id = NULL
    /\ slot_id_valid = FALSE
    /\ nonces_seen = {}
    /\ responder_nonce = NULL
    /\ requester_nonce = NULL
    /\ key_source = NULL
    /\ requester_context = NULL
    /\ requester_context_in_response = NULL
    /\ messages = {}
    /\ endpoint_state = [req |-> [conn_state |-> NULL, auth_phase |-> "NONE"],
                         resp |-> [conn_state |-> NULL, auth_phase |-> "NONE"]]

(* ============ Actions ============ *)

(* Family 1, 3: RequesterSendChallenge
   Sends CHALLENGE with slot_id and nonce.
   Maps to: libspdm_req_challenge.c:119-211, specifically lines 119-127 (nonce gen),
            lines 134-143 (context setup), lines 196-213 (slot_id validation).
*)
RequesterSendChallenge(req_slot_id, version_neg) ==
    /\ spdm_version = version_neg
    /\ ValidSlotIDForVersion(req_slot_id, version_neg)
    /\ connection_state = NULL  \* Initial state
    /\ authentication_phase = "NONE"

    \* Line 119-127: Generate requester nonce
    /\ requester_nonce' \in 1..100
    /\ requester_nonce' \notin nonces_seen

    \* Line 196-213: Validate slot_id (Family 3: version-specific check)
    /\ slot_id' = req_slot_id
    /\ IF version_neg >= SPDM_VERSION_10
       THEN /\ IF req_slot_id = 255
               THEN TRUE  \* Public key mode, param1 should be 0xF
               ELSE TRUE  \* Specific slot mode
            /\ slot_id_valid' = TRUE
       ELSE /\ slot_id_valid' = FALSE

    \* Line 134-143: Handle request context (Family 6, SPDM 1.3+)
    /\ IF VersionSupportsContext(version_neg)
       THEN requester_context' \in 0..255
       ELSE requester_context' = NULL

    /\ nonces_seen' = nonces_seen \cup {requester_nonce'}
    /\ authentication_phase' = "ONE_WAY_STARTED"
    /\ active_transcript' = "MAIN"
    /\ messages' = messages \cup {[type |-> "CHALLENGE",
                                    slot_id |-> slot_id',
                                    nonce |-> requester_nonce',
                                    context |-> requester_context']}
    /\ endpoint_state' = SetEndpointState(Requester,
                          [conn_state |-> "CHALLENGED", auth_phase |-> "ONE_WAY_STARTED"])
    /\ UNCHANGED <<connection_state, spdm_version, message_c, message_mut_c, signature_valid,
                    key_source, requester_context_in_response, responder_nonce>>

(* Family 1, 2, 3, 5, 6: ResponderHandleChallenge
   Processes CHALLENGE request, generates CHALLENGE_AUTH response.
   Maps to: libspdm_rsp_challenge_auth.c:95-342
*)
ResponderHandleChallenge ==
    \E msg \in messages:
        msg.type = "CHALLENGE" =>
        /\ slot_id' = msg.slot_id

        \* Line 95-126: Validate slot_id per version (Family 3)
        /\ IF spdm_version >= SPDM_VERSION_10
           THEN /\ IF msg.slot_id = 255
                   THEN key_source' = PUBLIC_KEY_ONLY  \* Family 5
                   ELSE key_source' = CERT_CHAIN       \* Family 5
                /\ slot_id_valid' = ValidSlotIDForVersion(msg.slot_id, spdm_version)
           ELSE /\ slot_id_valid' = FALSE

        \* Line 225-230: Generate responder nonce (Family 4)
        /\ responder_nonce' \in 1..100
        /\ responder_nonce' \notin nonces_seen
        /\ nonces_seen' = nonces_seen \cup {responder_nonce'}

        \* Line 291-295: Handle context echo (Family 6, SPDM 1.3+)
        /\ IF VersionSupportsContext(spdm_version)
           THEN requester_context_in_response' = msg.context
           ELSE requester_context_in_response' = NULL

        \* Line 312-326: Append to message buffer for signature (Family 2)
        /\ message_c' = Append(message_c, msg)
        /\ active_transcript' = "MAIN"

        \* Line 336-338: Determine if mutual auth requested (Family 1)
        /\ LET mutual_auth_req == TRUE  \* Assume mutual auth is requested for now
           IN
           /\ IF ~mutual_auth_req
              THEN /\ connection_state' = AUTHENTICATED
                   /\ authentication_phase' = "ONE_WAY_COMPLETE"
              ELSE /\ connection_state' = CHALLENGED
                   /\ authentication_phase' = "MUTUAL_IN_PROGRESS"

        /\ signature_valid' = TRUE  \* Simplified: assume sig verification succeeds
        /\ messages' = (messages \ {msg}) \cup
                       {[type |-> "CHALLENGE_AUTH",
                         slot_id |-> slot_id',
                         nonce |-> responder_nonce',
                         context |-> requester_context_in_response',
                         mutual_auth_req |-> TRUE]}
        /\ endpoint_state' = SetEndpointState(Responder,
                              [conn_state |-> connection_state',
                               auth_phase |-> authentication_phase'])
        /\ UNCHANGED <<spdm_version, message_mut_c, requester_nonce, requester_context>>

(* Family 1, 2: RequesterHandleChallengeAuth
   Processes CHALLENGE_AUTH response. This is where Family 1 race occurs:
   requester sets connection_state to AUTHENTICATED before mutual auth completes.
   Maps to: libspdm_req_challenge.c:249-380
*)
RequesterHandleChallengeAuth ==
    \E msg \in messages:
        msg.type = "CHALLENGE_AUTH" =>
        /\ authentication_phase = "ONE_WAY_STARTED"

        \* Line 249-258: Verify hash based on key source (Family 5)
        /\ IF msg.slot_id = 255
           THEN key_source' = PUBLIC_KEY_ONLY
           ELSE key_source' = CERT_CHAIN

        \* Line 265-267: Verify responder nonce
        /\ responder_nonce' = msg.nonce

        \* Line 336-346: Verify context echo if SPDM 1.3+ (Family 6)
        /\ IF VersionSupportsContext(spdm_version)
           THEN requester_context_in_response' = msg.context
           ELSE requester_context_in_response' = NULL

        \* Line 380: CRITICAL BUG POINT (Family 1)
        \* Requester sets AUTHENTICATED immediately after signature verify,
        \* BEFORE encapsulated mutual auth request is sent (line 389).
        \* This creates a window where requester.connection_state != responder.connection_state
        /\ connection_state' = AUTHENTICATED
        /\ authentication_phase' = "ONE_WAY_COMPLETE"  \* Should be MUTUAL_IN_PROGRESS if mutual_auth_req

        /\ message_c' = Append(message_c, msg)
        /\ messages' = messages \ {msg}

        \* If mutual auth requested, send encapsulated request (line 389)
        /\ IF msg.mutual_auth_req
           THEN /\ messages' = messages \cup {[type |-> "ENCAP_CHALLENGE",
                                                from |-> Requester,
                                                to |-> Responder]}
           ELSE UNCHANGED messages

        /\ endpoint_state' = SetEndpointState(Requester,
                              [conn_state |-> connection_state',
                               auth_phase |-> authentication_phase'])
        /\ UNCHANGED <<spdm_version, message_mut_c, slot_id, slot_id_valid,
                        nonces_seen, requester_nonce, active_transcript>>

(* Family 2: ResponderHandleEncapChallenge
   Handles encapsulated challenge request (mutual auth path).
   Maps to: libspdm_rsp_encap_challenge.c:62-75
*)
ResponderHandleEncapChallenge ==
    \E msg \in messages:
        msg.type = "ENCAP_CHALLENGE" =>
        /\ authentication_phase = "MUTUAL_IN_PROGRESS"

        \* Line 62-75: Reset and use separate transcript for mutual auth (Family 2)
        /\ message_mut_c' = Append(message_mut_c, msg)
        /\ active_transcript' = "MUTUAL_AUTH"

        \* Generate encapsulated challenge response
        /\ messages' = (messages \ {msg}) \cup {[type |-> "ENCAP_CHALLENGE_AUTH",
                                                  from |-> Responder,
                                                  to |-> Requester]}
        /\ UNCHANGED <<connection_state, spdm_version, message_c, signature_valid,
                        authentication_phase, slot_id, slot_id_valid, nonces_seen,
                        responder_nonce, requester_nonce, key_source,
                        requester_context, requester_context_in_response, endpoint_state>>

(* Family 1, 2: RequesterHandleEncapChallengeAuth
   Processes encapsulated challenge response and completes mutual auth.
   Maps to: libspdm_req_challenge.c after line 389
*)
RequesterHandleEncapChallengeAuth ==
    \E msg \in messages:
        msg.type = "ENCAP_CHALLENGE_AUTH" =>
        /\ authentication_phase = "ONE_WAY_COMPLETE"  \* Actually should check for MUTUAL_IN_PROGRESS

        \* Process mutual auth response (Family 2: use mutual transcript)
        /\ message_mut_c' = Append(message_mut_c, msg)
        /\ active_transcript' = "MUTUAL_AUTH"

        \* Complete mutual authentication
        /\ authentication_phase' = "FULLY_AUTHENTICATED"
        /\ connection_state' = FULLY_AUTH  \* Both sides now agree (after this action)

        /\ messages' = messages \ {msg}
        /\ endpoint_state' = SetEndpointState(Requester,
                              [conn_state |-> FULLY_AUTH,
                               auth_phase |-> "FULLY_AUTHENTICATED"])
        /\ UNCHANGED <<spdm_version, message_c, signature_valid, slot_id,
                        slot_id_valid, nonces_seen, responder_nonce, requester_nonce,
                        key_source, requester_context, requester_context_in_response>>

(* Receive message (non-deterministic delivery) *)
ReceiveMessage(src, dst, msg) ==
    /\ msg \in messages
    /\ TRUE  \* Always allowed (message is already in flight)

(* Drop message (fault injection - optional) *)
DropMessage ==
    \/ \E msg \in messages:
       messages' = messages \ {msg}
    \/ UNCHANGED messages

(* ============ Next ============ *)

Next ==
    \/ \E slot \in 0..7, ver \in {SPDM_VERSION_10, SPDM_VERSION_11, SPDM_VERSION_12, SPDM_VERSION_13}:
       RequesterSendChallenge(slot, ver)
    \/ RequesterSendChallenge(255, SPDM_VERSION_10)  \* Special case: public key mode
    \/ ResponderHandleChallenge
    \/ RequesterHandleChallengeAuth
    \/ ResponderHandleEncapChallenge
    \/ RequesterHandleEncapChallengeAuth
    \/ DropMessage

(* ============ Invariants ============ *)

(* Standard Safety Invariants *)

TypeInvariant ==
    /\ connection_state \in {NULL, AUTHENTICATED, CHALLENGED, FULLY_AUTH}
    /\ spdm_version \in {SPDM_VERSION_10, SPDM_VERSION_11, SPDM_VERSION_12, SPDM_VERSION_13}
    /\ authentication_phase \in {"NONE", "ONE_WAY_STARTED", "ONE_WAY_COMPLETE",
                                  "MUTUAL_IN_PROGRESS", "FULLY_AUTHENTICATED"}
    /\ active_transcript \in {"NONE", "MAIN", "MUTUAL_AUTH"}
    /\ slot_id_valid \in {TRUE, FALSE}
    /\ key_source \in {NULL, CERT_CHAIN, PUBLIC_KEY_ONLY}
    /\ nonces_seen \subseteq Nat

(* Bug Family 1: State Consistency
   At any point, if requester.connection_state == AUTHENTICATED and mutual_auth is requested,
   then responder.authentication_phase must NOT be ONE_WAY_COMPLETE.
   This invariant detects the state transition race.
*)
StateConsistency ==
    /\ authentication_phase = "ONE_WAY_COMPLETE" \/
       authentication_phase = "FULLY_AUTHENTICATED" \/
       authentication_phase = "MUTUAL_IN_PROGRESS" \/
       authentication_phase = "ONE_WAY_STARTED" \/
       authentication_phase = "NONE"
    \* Strengthened: if requester has set connection_state to AUTHENTICATED,
    \* and there's a mutual auth in progress, they should be in sync
    /\ IF connection_state = AUTHENTICATED /\ authentication_phase = "MUTUAL_IN_PROGRESS"
       THEN FALSE  \* This is the bug: state mismatch
       ELSE TRUE

(* Bug Family 2: Transcript Integrity
   Ensure that signature verification uses the correct transcript:
   - MAIN transcript for one-way auth
   - MUTUAL transcript for mutual auth
   - No cross-contamination
*)
TranscriptIntegrity ==
    /\ IF authentication_phase \in {"ONE_WAY_STARTED", "ONE_WAY_COMPLETE"}
       THEN active_transcript = "MAIN"
       ELSE IF authentication_phase \in {"MUTUAL_IN_PROGRESS", "FULLY_AUTHENTICATED"}
            THEN active_transcript \in {"MAIN", "MUTUAL_AUTH"}  \* Both may be used in sequence
            ELSE TRUE

(* Bug Family 3: Slot ID Consistency
   If CHALLENGE uses slot_id S, then CHALLENGE_AUTH must reference the same slot
   (possibly in version-specific encoding).
*)
SlotIDMatch ==
    /\ slot_id = NULL \/
       (slot_id >= 0 /\ slot_id < 8) \/
       slot_id = 255

(* Bug Family 4: Nonce Freshness
   Each CHALLENGE in a session must contain a nonce not seen before.
   Since we track responder_nonce and requester_nonce, they should be distinct
   and appear exactly once in nonces_seen per session.
*)
NonceFreshness ==
    /\ IF responder_nonce /= NULL
       THEN responder_nonce \in nonces_seen
       ELSE TRUE
    /\ IF requester_nonce /= NULL
       THEN requester_nonce \in nonces_seen
       ELSE TRUE

(* Bug Family 5: Key Source Consistency
   If requester selects key_source CERT_CHAIN, responder must generate hash from CERT_CHAIN.
   If requester selects key_source PUBLIC_KEY_ONLY, responder must generate hash from PUBLIC_KEY_ONLY.
*)
KeySourceConsistency ==
    /\ key_source \in {NULL, CERT_CHAIN, PUBLIC_KEY_ONLY}

(* Bug Family 6: Context Echo (SPDM 1.3+)
   If request contains requester_context C, and version >= 1.3,
   then response must echo C byte-for-byte.
*)
ContextEcho ==
    /\ IF VersionSupportsContext(spdm_version) /\ requester_context /=NULL
       THEN /\ requester_context_in_response = requester_context \/
               requester_context_in_response = NULL  \* Not yet received
           ELSE TRUE

(* Cross-cutting Invariant: Signature Verification
   Signature should only be valid after proper transcript setup.
*)
SignatureVerificationInvariant ==
    /\ signature_valid = TRUE =>
       (active_transcript \in {"MAIN", "MUTUAL_AUTH"})

Invariant1 == StateConsistency
Invariant2 == TranscriptIntegrity
Invariant3 == SlotIDMatch
Invariant4 == NonceFreshness
Invariant5 == KeySourceConsistency
Invariant6 == ContextEcho
Invariant7 == SignatureVerificationInvariant
Invariant8 == TypeInvariant

====
