#!/bin/bash
args=" $* "

if [[ "$args" == *" PING "* ]]; then
    echo PONG
elif [[ "$args" == *" CONFIG_DB GET CONFIG_DB_INITIALIZED "* ]]; then
    echo 1
elif [[ "$args" == *"FEATURE|swss"*"has_per_asic_scope"* ]]; then
    echo true
elif [[ "$args" == *"FEATURE|swss"*"has_global_scope"* ]]; then
    echo false
elif [[ "$args" == *"FEATURE|swss"*" state"* || "$args" == *"FEATURE|swss"*" STATE"* ]]; then
    echo enabled
elif [[ "$args" == *"FEATURE|"*"has_per_asic_scope"* || "$args" == *"FEATURE|"*"has_global_scope"* ]]; then
    echo false
elif [[ "$args" == *"FEATURE|"*" state"* || "$args" == *"FEATURE|"*" STATE"* ]]; then
    echo disabled
elif [[ "$args" == *"FAST_RESTART_ENABLE_TABLE|system"*" enable"* ]]; then
    echo false
elif [[ "$args" == *"WARM_RESTART_ENABLE_TABLE|system"*" enable"* ]]; then
    echo true
elif [[ "$args" == *"WARM_RESTART_TABLE|"*" state"* ]]; then
    if [[ "${SPECULA_COMPONENT_MODE:-reconciled}" == "reconciled" ]]; then
        echo reconciled
    else
        echo restoring
    fi
fi
exit 0
